pipeline {
    agent any
    environment {
        IMAGE = 'baltig.infn.it:4567/epicscs/epicsmng'
    }
    stages {
        stage('Test epics-calc versions') {
            matrix {
                agent {
                    kubernetes { 
                        yaml """
                        apiVersion: v1
                        kind: Pod
                        spec:
                          imagePullSecrets:
                            - name: baltig-reg-key
                          containers:
                            - name: builder
                              image: ${IMAGE}:${BRANCH_NAME}-${OS}
                              command:
                                - cat
                              tty: true
                        """
                    }
                }
                axes {
                    axis {
                        name 'OS'
                        values 'ubuntu20.04', 'ubuntu22.04', 'ubuntu24.04', 'almalinux9', 'almalinux10'
                    }
                    axis {
                        name 'BASE'
                        values 'R7.0.10', 'R3.16.2', 'R3.15.9', 'R3.14.12.8'
                    }
                    axis {
                        name 'CALC'
                        values 'R3-7-5', 'R3-7-4', 'R3-7-3', 'R3-7-2', 'R3-7-1'
                    }
                }
                stages {
                    stage('Test calc') {
                        steps {
                            container('builder') {
                                sh "printf '%s' 'base = ${BASE}\n' > epicsmng.conf"
                                sh "printf '%s' 'calc = ${CALC}' >> epicsmng.conf"
                                sh 'epicsmng makemodules -v -t epicsmng.conf'
                            }
                        }
                    }
                }
            }
        }
    }
}