pipeline {
    agent any
    environment {
        IMAGE = 'baltig.infn.it:4567/epicscs/epicsmng'
    }
    stages {
        stage('Test epics-motor versions on ubuntu') {
            matrix {
                agent {
                    kubernetes { 
                        yaml """
                        apiVersion: v1
                        kind: Pod
                        spec:
                          imagePullSecrets:
                            - name: baltig-reg-key
                          containers:
                            - name: builder
                              image: ${IMAGE}:${BRANCH_NAME}-${OS}
                              command:
                                - cat
                              tty: true
                        """
                    }
                }
                axes {
                    axis {
                        name 'OS'
                        values 'ubuntu20.04', 'ubuntu22.04', 'ubuntu24.04'
                    }
                    axis {
                        name 'BASE'
                        values 'R7.0.10', 'R3.16.2', 'R3.15.9', 'R3.14.12.8'
                    }
                    axis {
                        name 'ASYN'
                        values 'R4-45', 'R4-44-2', 'R4-43'
                    }
                    axis {
                        name 'MOTOR'
                        values 'R7-4', 'R7-3-1', 'R7-3', 'R7-2-2', 'R7-2-1', 'R6-11'
                    }
                }
                stages {
                    stage('Test motor') {
                        steps {
                            container('builder') {
                                sh "printf '%s' 'base = ${BASE}\n' > epicsmng.conf"
                                sh "printf '%s' 'asyn = ${ASYN}\n' >> epicsmng.conf"
                                sh "printf '%s' 'motor = ${MOTOR}' >> epicsmng.conf"
                                sh 'epicsmng makemodules -v -t epicsmng.conf'
                            }
                        }
                    }
                }
            }
        }
        stage('Test epics-motor versions on almalinux') {
            matrix {
                agent {
                    kubernetes { 
                        yaml """
                        apiVersion: v1
                        kind: Pod
                        spec:
                          imagePullSecrets:
                            - name: baltig-reg-key
                          containers:
                            - name: builder
                              image: ${IMAGE}:${BRANCH_NAME}-${OS}
                              command:
                                - cat
                              tty: true
                        """
                    }
                }
                axes {
                    axis {
                        name 'OS'
                        values 'almalinux9', 'almalinux10'
                    }
                    axis {
                        name 'BASE'
                        values 'R7.0.10', 'R3.16.2', 'R3.15.9', 'R3.14.12.8'
                    }
                    axis {
                        name 'ASYN'
                        values 'R4-45', 'R4-44-2', 'R4-43'
                    }
                    axis {
                        name 'MOTOR'
                        values 'R7-4', 'R7-3-1', 'R7-3', 'R7-2-2', 'R7-2-1', 'R6-11'
                    }
                }
                stages {
                    stage('Test motor') {
                        steps {
                            container('builder') {
                                sh "printf '%s' 'base = ${BASE}\n' > epicsmng.conf"
                                sh "printf '%s' 'asyn = ${ASYN}\n' >> epicsmng.conf"
                                sh "printf '%s' 'motor = ${MOTOR}' >> epicsmng.conf"
                                sh 'epicsmng makemodules -v -t epicsmng.conf'
                            }
                        }
                    }
                }
            }
        }
    }
}