stages:
  - test
  - deploy
   
shellcheck:
  stage: test
  image: koalaman/shellcheck-alpine:stable
  variables:
  #ignore warnings on unused variables and non costant source (imported files)
    SHELLCHECK_OPTS: "-e SC2034,SC1090"
  script: 
  #run shellcheck on all scripts
    - shellcheck ./epicsmng
    - shellcheck ./install.sh
    - shellcheck ./uninstall.sh
    - shellcheck ./utils/epicsmng-completion.bash
    - shellcheck ./utils/completion_include.bash

build:
  stage: deploy
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  script:
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor --context $CI_PROJECT_DIR \
      --dockerfile $CI_PROJECT_DIR/docker/Dockerfile.ubuntu \
      --destination $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG-ubuntu \
      --destination $CI_REGISTRY_IMAGE:ubuntu
    - /kaniko/executor --context $CI_PROJECT_DIR \
      --dockerfile $CI_PROJECT_DIR/docker/Dockerfile.centos \
      --destination $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG-centos
      --destination $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG
      --destination $CI_REGISTRY_IMAGE:centos \
      --destination $CI_REGISTRY_IMAGE:latest
  #only:
  #  - tags