ARG OS_VERSION=20.04

FROM ubuntu:${OS_VERSION} AS install-epicsmng

# Add the epicsmng executable location to PATH
ARG HOME=/root
ENV HOME=${HOME}
ENV PATH=${PATH}:${HOME}/.local/bin

# Copy epicsmng code from repository
COPY ./utils /epicsmng/utils
COPY ./epicsmng ./install.sh /epicsmng/

# Install required packets to build code
# Install, clean source files and set the github mirror of the base to be used (faster)
RUN apt-get update \ 
    && apt-get -y install \
        git \
        build-essential \
        libreadline-dev \
        wget \
        libc-dev-bin \
        re2c \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/* \
    && bash /epicsmng/install.sh \
    && rm -rf /epicsmng \
    && echo "base_url=\"https://github.com/epics-base/epics-base\"" \
        | install -D dev/stdin ${HOME}/.config/epicsmng/settings/user.settings

EXPOSE 5064/tcp
EXPOSE 5064/udp
EXPOSE 5065/udp