pipeline {
    agent any
    stages {
        stage('Test epics-base versions') {
            matrix {
                axes {
                    axis {
                        name 'OS'
                        values 'ubuntu20.04', 'ubuntu22.04', 'ubuntu24.04', 'almalinux9', 'almalinux10'
                    }
                    axis {
                        name 'BASE'
                        values 'R7.0.10', 'R7.0.9', 'R7.0.8.1', 'R7.0.8', 'R7.0.7', 'R3.16.2', 'R3.15.9', 'R3.14.12.8'
                    }
                }
                stages {
                    stage('Test epics-base') {
                        steps {
                            script {
                                def pod = load "../pod.groovy"
                                def tag = "${BRANCH_NAME}-${OS}"
                                pod.epicsmngPod(tag) {
                                    node(POD_LABEL) {
                                        container('builder') {
                                            sh "printf '%s' 'base = ${BASE}' > epicsmng.conf"
                                            sh 'epicsmng makemodules -v epicsmng.conf'
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }
    }
}